MyTanoda.Web/Models/Diak.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MyTanoda.Web.Models
{
    // Form Model
    public class Diak
    {
        [Display(Name = "Diák ID")]
        [Required]
        public int Id { get; set; }
        
        [Display(Name = "Diák Neve")]
        [Required]
        public string Nev { get; set; }

        [Display(Name = "Diák NeMe")]
        [Required]
        public string Nem { get; set; }

        [Display(Name = "Diák születési dátuma")]
        [Required]
        public DateTime SzuletesiDatum { get; set; }
    }
}

MyTanoda.Web/Controllers/DiakController.cs
using AutoMapper;
using MyTanoda.BL.Services;
using MyTanoda.DA;
using MyTanoda.DA.Interfaces;
using MyTanoda.DA.Repositories;
using MyTanoda.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyTanoda.Web.Controllers
{
    public class DiakController : Controller
    {
        DiakService ds;
        IMapper mapper;
        DiakokViewModel vm;

        public DiakController()
        {
            MyTanodaDBEntities ctx = new MyTanodaDBEntities();
            DiakRepository diakRepo = new DiakRepository(ctx);
            ds = new DiakService(diakRepo);

            mapper = MapperFactory.CreateMapper();
            vm = new DiakokViewModel();
            vm.EditedDiak = new Diak();
            var diakok = ds.GetAll();
            vm.ListofDiakok = mapper.Map<IList<Diakok>, List<Models.Diak>>(diakok);
            

        }

        private Diak GetDiak(int id)
        {
            var egyDiak = ds.GetOne(id);
            return mapper.Map<Diakok,Diak>(egyDiak);

        }

        // GET: Diak
        public ActionResult Index()
        {
            ViewData["editAction"] = "AddNew";
            return View("DiakIndex",vm);
        }

        // GET: Diak/Details/5
        public ActionResult Details(int id)
        {
            return View("DiakDetails", GetDiak(id));
        }

        // 1x Delete, 1x Edit+GET, 1x Edit+Post

        // GET: /Cars/Remove/5
        public ActionResult Remove(int id)
        {
            TempData["editResult"] = "Delete Fail";
            try
            {
                ds.Delete(id);
            }
            catch (Exception)
            {
                TempData["editResult"] = "Delete failed";
            }
            return RedirectToAction(nameof(Index));
        }
        // GET /Cars/Edit/5
        public ActionResult Edit(int id)
        {
            ViewData["editAction"] = "Edit";
            vm.EditedDiak = GetDiak(id);
            return View("DiakIndex", vm);
        }

        // POST /Cars/Edit
        [HttpPost]
        public ActionResult Edit(Diak diak, string editAction)
        {
            if (ModelState.IsValid && diak != null)
            {
                TempData["editResult"] = "Delete OK!";
                if (editAction == "AddNew")
                {
                    var lastID = ds.GetAll()
                        .OrderBy(x => x.id)
                        .Reverse()
                        .Select(x => x.id)
                        .Take(1);

                    int new_id = Convert.ToInt32(lastID) + 1;

                    var uj_adatok = new Diakok()
                    {
                        id = new_id,
                        nev = diak.Nev,
                        nem = diak.Nem,
                        szuletesi_datum = diak.SzuletesiDatum,
                    };
                    ds.Create(uj_adatok);
                } else
                {
                    try
                    {
                        var uj_adatok = new Diakok()
                        {
                            id = diak.Id,
                            nev = diak.Nev,
                            nem = diak.Nem,
                            szuletesi_datum = diak.SzuletesiDatum,
                        };
                        ds.Update(uj_adatok);
                    }
                    catch
                    {
                        TempData["editResult"] = "EDIT Failed!";
                    }
                }
            }
            else 
            {
                ViewData["editAction"] = "Edit";
                vm.EditedDiak = diak;
                return View("DiakIndex", vm);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

MyTanoda.Web/Views/Diak/DiakDetails.cshtml
@model MyTanoda.Web.Models.Diak
@{
    ViewBag.Title = "DiakDetails";
}

<h2>Datasheet of one Diak</h2>

@Html.ActionLink("Back to the list", "Index");

<table>
    <tr>
        <td>Diak ID</td>
        <td>@Model.Id</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Nev)</td>
        <td>@Html.DisplayFor(m => m.Nev)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Nem)</td>
        <td>@Html.DisplayFor(m => m.Nem)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.SzuletesiDatum)</td>
        <td>@Html.DisplayFor(m => m.SzuletesiDatum)</td>
    </tr>
</table>

MyTanoda.Web/Views/Diak/DiakEdit.cshtml
@model MyTanoda.Web.Models.Diak

<h2>Edit one Diak</h2>

@using (Html.BeginForm("Edit", "Diak"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()
    //CSRF = Cross Site Request Forgery

    @Html.HiddenFor(m=>m.Id)
    @Html.Hidden("editAction", ViewData["editAction"].ToString());


    <div class="editor-label">@Html.LabelFor(m => m.Nev)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Nev)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Nem)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Nem)</div>

    <div class="editor-label">@Html.LabelFor(m => m.SzuletesiDatum)</div>
    <div class="editor-field">@Html.EditorFor(m => m.SzuletesiDatum)</div>

    <input type="submit" value="SEND" />
}

MyTanoda.Web/Views/Diak/DiakIndex.cshtml
@model MyTanoda.Web.Models.DiakokViewModel
@{
    ViewBag.Title = "Diak Index";
}

<h2>Diak Index</h2>

<p style="color:red;font-weight:bold">@TempData["editResult"]</p>

@Html.Partial("DiakEdit", Model.EditedDiak)

@Html.Partial("DiakList", Model.ListofDiakok)

MyTanoda.Web/Views/Diak/DiakList.cshtml
@model IEnumerable<MyTanoda.Web.Models.Diak>

<h2>List of Diak</h2>

@if (Model.Count() == 0)
{
    <p>No data in the database!</p>
}
else
{
<table border="1">
    <tr>
        <th>@Html.DisplayNameFor(m=>m.First().Id))</th>
        <th>@Html.DisplayNameFor(m=>m.First().Nev))</th>
        <th>@Html.DisplayNameFor(m=>m.First().SzuletesiDatum))</th>
        <th>Datasheet</th>
        <th>Delete</th>
        <th>Edit</th>
    </tr>
    @foreach (var item in Model)
    {
<tr>
    <td>@Html.DisplayFor(m => item.Id) </td>
    <td>@Html.DisplayFor(m => item.Nev)</td>
    <td>@Html.DisplayFor(m => item.SzuletesiDatum)</td>
    <td>@Html.ActionLink("[SHOW]", "Details", new { Id = item.Id })</td>
    <td>@Html.ActionLink("[DEL]", "Remove", new { Id = item.Id })</td>
    <td>@Html.ActionLink("[EDIT]", "Edit", new { Id = item.Id })</td>
</tr>
    }
</table>
}